package com.myapplication.common

object Constants {
    val INCREASEADAPTER = "INCREASEADAPTER"
    val RESETADAPTER = "RESETADAPTER"
    val FULL_AZAN = "FULL_AZAN"
    val TAKBIRAT_ONLY = "TAKBIRAT_ONLY"
    val AZANMESHARY = "AZANMESHARY"
    val AZANELHOSARY = "AZANELHOSARY"
    val OPENSOURA = "OPENSOURA"
    val LONGCLICK = "LONGCLICK"
    val ONCLICK = "ONCLICK"

}